### ISSUE TITLE
Didn't show tips for plugin-git

### ISSUE THREAD

**Issue by 404cn** [gazorby/fish-abbreviation-tips#19]
**Describe the bug**
Didn't show tips for [plugin-git](https://github.com/jhillyerd/plugin-git)

**To Reproduce**
Install these two plugin and run `git add .` ?

**Expected behavior**
Show `ga =>> git add .`

**Screenshots**
<img width="322" alt="Screen Shot 2021-11-10 at 10 21 47 AM" src="https://user-images.githubusercontent.com/24653356/141037931-1ab2febb-bfda-480d-8862-73d5321882b5.png">

**System (please complete the following information):**
fish, version 3.3.1
MacOS 12.0.1

**Comment by luong-komorebi** [comment]
can confirm this bug is true. Also wont work for kubernetes or any thing else.

However, it will work if you trigger __abbr_tips_init
So maybe what s needed to be done here is installing all other plugins that deals with abbreviation after install this plugin.

Or, have some way to trigger __abbr_tips_init that affect the results

![image](https://user-images.githubusercontent.com/15828926/141431223-cb42f4b2-8f5c-4329-90c2-203ed357629d.png)
